name: CI checks

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources 
      uses: actions/checkout@v3
      with:
        submodules: recursive  
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 15
    - name: Run cargo fmt
      if: always()
      run: cargo fmt --all -- --check
    - name: Run cargo clippy
      if: always()
      run: cargo clippy --workspace --tests --bins -- -D warnings
    - name: Run tests
      run: cargo test --verbose  
  linux-x86-64:
    name: Linux x86-64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 15    
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test --workspace
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: olac-linux-x86-64
        path: ./target/debug/olac
  mac-intel:
    name: Mac Intel
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 15      
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test --workspace
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: olac-mac-intel
        path: ./target/debug/olac 
  mac-arm:
    name: Mac Arm
    runs-on: macos-13-arm64
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 15
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test --workspace
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/olac
        asset_name: olac-mac-arm
        tag: ${{ github.ref }}    
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 15
    - name: Build
      run: cargo build 
    - name: Run tests
      run:  cargo test --workspace
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: olac.exe
        path: ./target/debug/olac.exe 
