name: CI checks

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources 
      uses: actions/checkout@v3
      with:
        submodules: recursive  
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 15
    - name: Run cargo fmt
      if: always()
      run: cargo fmt --all -- --check
    - name: Run cargo clippy
      if: always()
      run: cargo clippy --workspace --tests --bins -- -D warnings
    - name: Run tests
      run: cargo test --verbose  
  linux-x86-64:
    name: Linux x86-64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 15    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --workspace
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: olac-linux-x86-64
        path: ./target/debug/olac
  mac-intel:
    name: Mac Intel
    runs-on: macos-12
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 15      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --workspace
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: olac-mac-intel
        path: ./target/debug/olac     
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Rust nightly  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Download LLVM
      run: curl -sSL -o c:\llvm.7z https://github.com/c3lang/win-llvm/releases/download/llvm_15_0_6/llvm-15.0.6-windows-amd64-msvc17-msvcrt-dbg.7z
    - name: Extract LLVM
      run: |
        7z x c:\llvm.7z -oc:/
        move c:\llvm-15.0.6-windows-amd64-msvc17-msvcrt-dbg c:\llvm
    - name: Add LLVM to Path
      run: echo "c:\llvm\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Build
      run: llvm-config.exe --version && cargo build --verbose
    - name: Run tests
      run:  cargo test --verbose --workspace
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: olac.exe
        path: ./target/debug/olac.exe 
